kind: pipeline
type: docker
name: check-java base

steps:
  - name: check
    image: adoptopenjdk/openjdk14:alpine
    volumes:
      - name: cache
        path: ~/.gradle
    commands:
      - ./gradlew check
